spring:
  application:
    name: libro-contable-service
  datasource:
    url: jdbc:h2:mem:libro_contable_service_db
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
server:
  port: 0
