server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: cliente-service
          uri: lb://cliente-service
          predicates:
            - Path=/cliente/**
        - id: producto-service
          uri: lb://producto-service
          predicates:
            - Path=/producto/**
        - id: stock-service
          uri: lb://stock-service
          predicates:
            - Path=/stock/**
        - id: venta-service
          uri: lb://venta-service
          predicates:
            - Path=/venta/**
        - id: libro-contable-service
          uri: lb://libro-contable-service
          predicates:
            - Path=/libro-contable/**
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
